defaults:
  - _self_
  - agent: baku
  - suite: droid
  - dataloader: droid
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: /home/bpatil/workspace/BAKU

# misc
seed: 2
device: cuda:1
save_video: false
save_train_video: false
use_tb: true
# wandb logging
use_wandb: false  # enable/disable wandb logging
wandb_project: "skill_sampling"  # wandb project name
wandb_run_name: ${now:%Y.%m.%d}_${experiment}_${experiment_label}  # wandb run name
batch_size: 128
validation_batch_size: 32
validate_every_steps: 100000

# experiment
obs_type: "pixels" # pixels, features
num_demos_per_task: 50
encoder_type: 'resnet' # base, resnet
policy_type: 'gpt' # mlp, gpt
policy_head: diffusion # deterministic, gmm, bet, diffusion, vqbet
use_proprio: true
use_language: true
use_actions: false
prompt: text # text, goal, intermediate_goal
eval: false
experiment: train
experiment_label: ${policy_head}
print_actor_summary: true
# action chunking
temporal_agg: true # aggregate actions over time
num_queries: 10
load_env: false

# expert dataset
expert_dataset: ${dataloader.bc_dataset}

# Load weights
load_bc: false
bc_weight: /home/bpatil/workspace/BAKU/baku/exp_local/2025.01.22_train/vqbet/213402_hidden_dim_256/snapshot/600000.pt

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}_${experiment}/${experiment_label}/${now:%H%M%S}_hidden_dim_${suite.hidden_dim}
  sweep:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm
